#!/usr/bin/env sh
case "$*" in
  *"/auth.json"*)
    if [ "${MONK_TEST_AUTH_BODY+x}" = "x" ]; then
      printf '%s\n' "$MONK_TEST_AUTH_BODY"
    else
      printf '%s\n' '{"signedIn":true}'
    fi
    ;;
  *"/plugin/nudge?type=signin"*)
    if [ -n "${MONK_TEST_NUDGE_LOG:-}" ]; then
      printf '%s\n' nudge >>"$MONK_TEST_NUDGE_LOG"
    fi
    printf '%s\n' '{}'
    ;;
  *)
    printf '%s\n' '{"resource":"http://127.0.0.1:7419/mcp"}'
    ;;
esac
